title: "!Aprende en casa ya!"
email: hola@aprendeencasaya.com
description: >- # this means to ignore newlines until "baseurl:"
  aprendeencasaya.com es  una página para ayudar a los padres en la díficil tarea
  de educar a nuestros hijos en casa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aprendeencasaya.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aprendeencasaya
google_analytics: UA-130293099-5
theme: minima
# disqus:
#   shortname: http-aprendeencasaya-com
plugins:
  - jekyll-feed