title: aprendeencasaya
email: benjamin@aspnetcoremaster.com
description: >- # this means to ignore newlines until "baseurl:"
  Matematicas para todos.
baseurl: "/aprendeencasaya" # the subpath of your site, e.g. /blog
url: "https://aspnetcoremaster.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jbenjamincc
google_analytics: UA-130293099-5
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
